Repository Qowaiv/Qowaiv, pull requests merged in 2023-02, with the labels that each got.

#301 Decorate string arguments representing regexes with [StringSyntax(StringSyntaxAttribute.Regex)]
  src/Qowaiv/OpenApi/OpenApiDataType.cs
  src/Qowaiv/OpenApi/OpenApiDataTypeAttribute.cs
Labels: enhancement

#302 Include github actions in dependabot.yml
  .github/dependabot.yml
Labels: security issue

#304 Clock: Store time and timezone in AsyncLocal<> instead of ThreadStatic.
  .editorconfig
  README.md
  specs/Qowaiv.Specs/Clock_specs.cs
  specs/Qowaiv.Specs/Obsolete_code.cs
  specs/Qowaiv.Specs/UUID_specs.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/DateSpanTest.cs
  src/Qowaiv/Clock.cs
  src/Qowaiv/Qowaiv.csproj
Labels: feature request

#305 Renaming of internals of Clock
  src/Qowaiv/Clock.cs
Labels: enhancement

#306 Solve issues reported by newly introduced Sonar static coce analysis rules
  .editorconfig
  specs/Qowaiv.Specs/UnitTests.OldStyle/Formatting/FormattingArgumentsCollectionTest.cs
  src/Qowaiv/Month.cs
Labels: enhancement
