Repository Qowaiv/Qowaiv, pull requests merged in 2023-01, with the labels that each got.

#285 Regexes should be CultureInvariant for Qowaiv
  src/Qowaiv/Text/RegOptions.cs
Labels: enhancement

#286 Drop Not.Null helper method
  shared/Not.cs
  src/Qowaiv.TestTools/Deserialize.cs
  src/Qowaiv.TestTools/FluentAssertions/QowaivDebuggerDisplayAssertions.cs
  src/Qowaiv.TestTools/Qowaiv.TestTools.csproj
  src/Qowaiv.TestTools/SerializeDeserialize.cs
  src/Qowaiv/Conversion/Customization/SvoTypeConverter.cs
  src/Qowaiv/Conversion/Identifiers/IdTypeConverter.cs
  src/Qowaiv/EmailAddressCollection.cs
  src/Qowaiv/Exceptions.cs
  src/Qowaiv/Extensions/System.Globalization.CultureInfo.cs
  src/Qowaiv/Extensions/System.IFormatProvider.cs
  src/Qowaiv/Extensions/System.Security.Cryptography.HashAlgorithm.cs
  src/Qowaiv/Extensions/System.String.cs
  src/Qowaiv/Extensions/System.Type.cs
  src/Qowaiv/Globalization/Country.cs
  src/Qowaiv/Identifiers/Id.cs
  src/Qowaiv/Json/OpenApiDataTypeAttribute.cs
  src/Qowaiv/Qowaiv.csproj
  src/Qowaiv/Text/CharSpan.cs
  src/Qowaiv/Unknown.cs
Labels: enhancement

#289 Remove invalid implicit casts from documentation
  README.md
Labels: enhancement

#292 Fix code coverage in build
  .github/workflows/build-test.yaml
Labels: bug, enhancement

#290 Implement InYear and InMonth for date types
  README.md
  specs/Qowaiv.Specs/Date_only_specs .cs
  specs/Qowaiv.Specs/Date_span_specs.cs
  specs/Qowaiv.Specs/Date_specs.cs
  specs/Qowaiv.Specs/Date_time_specs.cs
  specs/Qowaiv.Specs/Local_date_time_specs.cs
  src/Qowaiv/Date.cs
  src/Qowaiv/Extensions/System.DateOnly.cs
  src/Qowaiv/Extensions/System.DateTime.cs
  src/Qowaiv/LocalDateTime.cs
Labels: feature request

#261 Extend with .NET 7.0 support
  README.md
  props/package.props
  specs/Qowaiv.Specs/Formattable_specs.cs
  specs/Qowaiv.Specs/SVO_contract_specs.cs
  specs/Qowaiv.Specs/Statistics/Elo_specs.cs
  src/Qowaiv.Data.SqlClient/Qowaiv.Data.SqlClient.csproj
  src/Qowaiv.TestTools/Qowaiv.TestTools.csproj
  src/Qowaiv/Qowaiv.csproj
Labels: enhancement

#297 Mark all static IsValid(string) methods obsolete
  specs/Qowaiv.Specs/Chemistry/CAS_Registry_Number_specs.cs
  specs/Qowaiv.Specs/Email_address_format_specs.cs
  specs/Qowaiv.Specs/Email_address_specs.cs
  specs/Qowaiv.Specs/Financial/IBAN_specs.cs
  specs/Qowaiv.Specs/Percentage_specs.cs
  specs/Qowaiv.Specs/Postal_code_specs.cs
  specs/Qowaiv.Specs/Sex_specs.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Financial/AmountTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Financial/CurrencyTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Financial/MoneyTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Globalization/CountryTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/HouseNumberTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/IO/StreamSizeTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/LocalDateTimeTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Mathematics/FractionTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/MonthSpanTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Statistics/EloTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/Web/InternetMediaTypeTest.cs
  specs/Qowaiv.Specs/UnitTests.OldStyle/WeekDateTest.cs
  specs/Qowaiv.Specs/Year_specs.cs
  specs/Qowaiv.Specs/YesNo_specs.cs
  src/Qowaiv.Data.SqlClient/Generated/Timestamp.generated.cs
  src/Qowaiv/Generated/Chemistry/CasRegistryNumber.generated.cs
  src/Qowaiv/Generated/Date.generated.cs
  src/Qowaiv/Generated/DateSpan.generated.cs
  src/Qowaiv/Generated/EmailAddress.generated.cs
  src/Qowaiv/Generated/Financial/Amount.generated.cs
  src/Qowaiv/Generated/Financial/BusinessIdentifierCode.generated.cs
  src/Qowaiv/Generated/Financial/Currency.generated.cs
  src/Qowaiv/Generated/Financial/InternationalBankAccountNumber.generated.cs
  src/Qowaiv/Generated/Financial/Money.generated.cs
  src/Qowaiv/Generated/Gender.generated.cs
  src/Qowaiv/Generated/Globalization/Country.generated.cs
  src/Qowaiv/Generated/HouseNumber.generated.cs
  src/Qowaiv/Generated/IO/StreamSize.generated.cs
  src/Qowaiv/Generated/LocalDateTime.generated.cs
  src/Qowaiv/Generated/Mathematics/Fraction.generated.cs
  src/Qowaiv/Generated/Month.generated.cs
  src/Qowaiv/Generated/MonthSpan.generated.cs
  src/Qowaiv/Generated/Percentage.generated.cs
  src/Qowaiv/Generated/PostalCode.generated.cs
  src/Qowaiv/Generated/Sex.generated.cs
  src/Qowaiv/Generated/Statistics/Elo.generated.cs
  src/Qowaiv/Generated/Uuid.generated.cs
  src/Qowaiv/Generated/Web/InternetMediaType.generated.cs
  src/Qowaiv/Generated/WeekDate.generated.cs
  src/Qowaiv/Generated/Year.generated.cs
  src/Qowaiv/Generated/YesNo.generated.cs
Labels: feature request
