Repository Qowaiv/Qowaiv, pull requests merged in 2024-10, with the labels that each got.

#419 Provide attributes as internals
  src/Qowaiv/Diagnostics/Contracts/CollectionMutationAttribute.cs
  src/Qowaiv/Diagnostics/Contracts/FluentSyntaxAttribute.cs
  src/Qowaiv/Diagnostics/Contracts/ImpureAttribute.cs
  src/Qowaiv/Diagnostics/Contracts/InheritableAttribute.cs
  src/Qowaiv/Qowaiv.csproj
Labels: bug

#422 Add examples to the intellisense of Percentage.Create(), .Percent() a…
  specs/Qowaiv.Specs/Percentage_specs.cs
  src/Qowaiv/Extensions/Humanizer.Percentage.cs
  src/Qowaiv/Percentage.cs
  src/Qowaiv/Qowaiv.csproj
Labels: enhancement

#423 Fix Qowaiv.Diagnostics.Contracts Nuget package not being detected as an analyzer
  src/Qowaiv.Diagnostics.Contracts/Qowaiv.Diagnostics.Contracts.csproj
Labels: enhancement

#426 Qowaiv.Diagnostics.Contracts Fix ambiguous references & support < C#10
  src/Qowaiv.Diagnostics.Contracts/.editorconfig
  src/Qowaiv.Diagnostics.Contracts/Attributes/CollectionMutationAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyClassAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyEnumAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyInterfaceAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyStructAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyTestClassAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyTestEnumAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyTestInterfaceAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyTestStructAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/EmptyTypeAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/FluentSyntaxAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/ImpureAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/InheritableAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/MutableAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Attributes/WillBeSealedAttribute.cs
  src/Qowaiv.Diagnostics.Contracts/Qowaiv.Diagnostics.Contracts.csproj
Labels: bug

#427 Non continous SVO's are preferably not serialized for their default values
  README.md
  specs/Qowaiv.Specs/Json/ModifyTypeInfo_specs.cs
  src/Qowaiv/Json/ModifyTypeInfo.cs
  src/Qowaiv/Qowaiv.csproj
Labels: feature request
