Repository Qowaiv/Qowaiv, pull requests merged in 2024-09, with the labels that each got.

#410 Applied suggestions by .NET project file analyzers
  analyzers-config.ini
  props/common.props
  props/nopackage.props
  props/package.props
  specs/Qowaiv.Benchmarks/Qowaiv.Benchmarks.csproj
  specs/Qowaiv.Specs/Qowaiv.Specs.csproj
  src/Qowaiv.Data.SqlClient/Qowaiv.Data.SqlClient.csproj
  src/Qowaiv.Diagnostics.Contracts/Qowaiv.Diagnostics.Contracts.csproj
  src/Qowaiv.TestTools/Qowaiv.TestTools.csproj
  src/Qowaiv/Qowaiv.csproj
Labels: enhancement

#413 Fix code coverage pipeline
  .github/workflows/code-coverage.yml
Labels: enhancement

#415 Add ZeroIfNull as extension on INumberBase<TSelf>
  specs/Qowaiv.Specs/Extensions/Number_specs.cs
  src/Qowaiv/Extensions/System.Numerics.INumberBase.cs
  src/Qowaiv/Qowaiv.csproj
Labels: feature request

#416 Implement Sum and Average on Percentage
  specs/Qowaiv.Specs/Collection_extensions_specs.cs
  src/Qowaiv/Extensions/System.Linq.Enumerable.cs
  src/Qowaiv/Qowaiv.csproj
Labels: feature request

#417 Bug in wildcards with trailing chars at the end
  specs/Qowaiv.Specs/Text/Wild_card_pattern_specs.cs
  specs/Qowaiv.Specs/_Legacy/Text/WildcardPatternTest.cs
  src/Qowaiv/Qowaiv.csproj
  src/Qowaiv/Text/WildcardPattern.cs
Labels: bug
